# Site settings
title: Scris Game Studio
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scris.top" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
baidu-analysisï¼š 4a7701b5afbaa4089b4e2fbef17101f3

# User settings
username: Scris Game Studio
user_description: A game studio created by two boys who come from Hangzhou.
user_title: S
email: scrisqiu@hotmail.com
twitter_username: 
github_username:  scris
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
